name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out github repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Hardhat compile
        run: yarn compile

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        continue-on-error: true
        with:
          solc-version: 0.8.13
          ignore-compile: true
          node-version: 16
          target: "solidity/"
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
